version: "3.4"
services:
  # plex:
  #   image: linuxserver/plex:${PLEX_VERSION}
  #   container_name: plex
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - VERSION=docker
  #     - UMASK_SET=022 #optional
  #     - PLEX_CLAIM= #optional
  #   volumes:
  #     - ${ROOT}/config/plex:/config
  #     - ${ROOT}/downloads/series:/tv
  #     - ${ROOT}/downloads/movies:/movies
  #   restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    user: ${PUID}:${PGID}
    network_mode: "host"
    volumes:
      - ${ROOT}/config/jellyfin:/config
      - ${ROOT}/downloads/series:/tv
      - ${ROOT}/downloads/movies:/movies
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
    restart: "unless-stopped"
      
  sonarr:
    image: linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/downloads/series:/tv # tv shows folder
      - ${ROOT}/downloads/sonarr:/downloads # download folder
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    container_name: radarr
    image: linuxserver/radarr:${RADARR_VERSION}
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 `#optional`
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${ROOT}/downloads/movies:/movies
      - ${ROOT}/downloads/radarr:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:${BAZARR_VERSION}
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/downloads/movies:/movies # movies folder
      - ${ROOT}/downloads/series:/tv # tv shows folder
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:${JACKETT_VERSION}
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    ports:
      - 9117:9117
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge:${DELUGE_VERSION}
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${ROOT}/config/deluge:/config # config files
      - ${ROOT}/downloads:/downloads
    restart: unless-stopped

  # qbittorrent:
  #   image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
  #   container_name: qbittorrent
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - UMASK_SET=022
  #     - WEBUI_PORT=8080
  #     - PASSWORD=motdepasse
  #   volumes:
  #     - ${ROOT}/config/qbittorrent:/config
  #     - ${ROOT}/downloads:/downloads
  #   ports:
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 8080:8080
  #   restart: unless-stopped
  #   network_mode: service:vpn

  # vpn:
  #   image: dperson/openvpn-client:${OPENVPN_VERSION}
  #   container_name: vpn
  #   cap_add:
  #     - net_admin # required to modify network interfaces
  #   restart: unless-stopped
  #   volumes:
  #     - /dev/net:/dev/net:z # tun device
  #     - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
  #   security_opt:
  #     - label:disable
  #   ports:
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 8080:8080
  #   command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
    